[project]
name = "fma"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "bs4>=0.0.2",
    "feedparser>=6.0.12",
    "ordered-set>=4.1.0",
    "urllib3>=2.5.0",
    "requests>=2.32.5",
]
